export const PATH = {
    HOME: '/home',
    LOGIN: '/login',
    USER: '/user-management',
    BRAND: '/brand-management',
    BRAND_CREATE: '/brand-create-management',
    BRAND_EDIT: '/brand-management/:id',
    CATEGORY: '/category-management',
    CATEGORY_CREATE: '/category-create-management',
    CATEGORY_EDIT: '/category-management/:id',
    PRODUCT: '/product-management',
    PRODUCT_CREATE: '/product-create-management',
    PRODUCT_EDIT: '/product-management/:id',
    ORDER: '/order-management',
    STATISTIC: '/statistic',
}